### ISSUE TITLE
how can i install murty?

### ISSUE THREAD

**Issue by heiitu** [erikbohnsack/pmbm#2]
i have tried the command pip3 install ./murty and it is not work.  how can i solve the problem?
thx

**Comment by erikbohnsack** [comment]
I see now that the README is missing that you need to run `git submodule update` before running `pip3 install ./murty` @heiitu

**Comment by heiitu** [comment]
thanks a lot @erikbohnsack

**Comment by heiitu** [comment]
it seems that the command "git submodule update" dose not work. nothing was downloaded

**Comment by hyerim-mmc** [comment]
Hi I ran `git submodule update` and run `pip3 install ./murty` as you mentioned but the error came out. 
**Invalid requirement: './murty'** 
Can you give help for this?
