### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by zhanghm1995** [erikbohnsack/pmbm#3]
Hello, thanks for your wonderful work and it's so kind of you to open source.

When I try to run your code by putting all codes in `runforrest.ipynb` file together, I found it may miss some files, such as the `mot/fafe/showroom/showroom_all/showroom_bev_NN/logs/log-seq` specified by `log_root` variable and the `mot/fafe/showroom/weights_2019-05-03_14-01_epoch_110_fafe` file specified by `showroom_fafe` variable.

Could you offer some help and point out some clues to run your code to get the results like yours. 

Thanks a lot.

**Comment by erikbohnsack** [comment]
Hello! 

Both variables are just folders to put the logs in if I remember correctly, which if you change the variable to something which fits your file system shouldn't trouble you.

**Comment by erikbohnsack** [comment]
Or create the folders :man_shrugging:

**Comment by erikbohnsack** [comment]
A lot of the code in `runforrest.ipynb` are related to different configurations, logging and plotting. If you try to understand the code you should be able to run a much simpler version.

**Comment by zhanghm1995** [comment]
Thanks for your reply. 

I have run your project successfully and got the results like in your thesis. After reading this project, I want to know what the word  'Fafe' mean? In the `runforrest.ipynb` file, I found there are many variables like `FafeDetections`, `FafeMeasurements` and `FafeConfig` and so on. I can't get the 'fafe' meaning in dictionary.

**Comment by erikbohnsack** [comment]
Our deep learning version github.com/erikbohnsack/etenn was called FaFe during the actual work. When it was time to formalize it in the thesis and open source code we changed the name to etenn since FaFe didn't make any sense.
